# Generated by Django 3.0.8 on 2022-01-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220118_1610'),
        ('clientes', '0003_auto_20200806_1144'),
    ]

    operations = [
    ]
